### ISSUE TITLE
过滤器怎么使用? 比如我想过滤视频和图片

### ISSUE THREAD

**Issue by DipsySu** [alienjun/PhotoPicker#10]
过滤器怎么使用? 比如我想过滤视频和图片;

**Comment by alienjun** [comment]
可以自己配置过滤内容：
picker.assetsFilter = [ALAssetsFilter allPhotos];  

// Get all photos assets in the assets group.
+ (ALAssetsFilter *)allPhotos;
// Get all video assets in the assets group.
+ (ALAssetsFilter *)allVideos;
// Get all assets in the group.
+ (ALAssetsFilter *)allAssets;

**Comment by DipsySu** [comment]
3Q;
