### ISSUE TITLE
一点建议

### ISSUE THREAD

**Issue by Heisenbean** [alienjun/PhotoPicker#4]
框架不错,有几点建议  
1. 希望基于`Photos Framework`,[`Assets Library`](https://developer.apple.com/library/ios/documentation/AssetsLibrary/Reference/AssetsLibraryFramework/)真的不怎么好用,官方也IMPORTANT里也推荐iOS8之后使用`Photos Framework`.  
2. 布局其实也可以使用`Masonry`或`PureLayout`此类的Autolayout框架,毕竟大家都熟悉,但是通过VFL布局再修改有点麻烦.  
3. 相册单选的时候,添加编辑模式.

> 以上是个人使用时遇到的一些问题,希望框架更新下去,加油.

**Comment by alienjun** [comment]
谢谢你的建议。
1.我们希望兼容iOS7 但又不想为iOS8之后单独判断使用photos.framework,这无疑是增加了控件的复杂性，感觉暂时还没有必要。

2.关于布局使用Masonry，在之前的版本是有使用的，但出于考虑不是所有人都使用Masonry；所以不希望为了使用此控件而引入一个他们根本不想使用的框架。

3.不清楚你说的编辑模式是指什么，如果是想弹出独立编辑界面，可以通过设置多选图片数量=1，在点击确定后自己弹出自己开发的编辑界面。
