### ISSUE TITLE
AJPhotoPickerViewController 的loadView方法会提前调用

### ISSUE THREAD

**Issue by liweican1992** [alienjun/PhotoPicker#7]
在示例代码中单选图片哪里
设置筛选条件不起作用
`AJPhotoPickerViewController *picker = [[AJPhotoPickerViewController alloc] init];
    picker.assetsFilter = [ALAssetsFilter allPhotos];
`
因为在AJPhotoPickerViewController的init中调用了sele.view方法

`- (instancetype)init {`
  `self = [super init];`
  `if (self) {`
       `self.view.backgroundColor = [UIColor whiteColor];`
       `self.automaticallyAdjustsScrollViewInsets = NO;`
        `_maximumNumberOfSelection = 10;`
        `_minimumNumberOfSelection = 0;`
       `_assetsFilter = [ALAssetsFilter allAssets];`
        `_showEmptyGroups = NO;`
        `_selectionFilter = [NSPredicate predicateWithValue:YES];`
  `}`
   `return self;`
`}`
会导致提前调用loadview，然后调用setupGroupView方法

`- (void)loadView {`
   `[super loadView];`

```
`[self setupNavBar];`
```

  `[self setupPhotoListView];`
  `[self setupGroupView];`
`}`
在这时候还未设置assetsFilter 
应该把init中self.view方法放到viewDidloaded或者loadView中

**Comment by alienjun** [comment]
感谢反馈
