### ISSUE TITLE
isSelected always false

### ISSUE THREAD

**Issue by ismaiI1** [alienjun/PhotoPicker#8]
`[self.indexPathsForSelectedItems containsObject:self.assets[indexPath.row]];` always return false. how can i check `indexPathsForSelectedItems` contains object?

**Comment by alienjun** [comment]
selected a new asset  [self.indexPathsForSelectedItems containsObject:] return false. because the asset not in self.indexPathsForSelectedItems; but you unselected the asset, the asset  already exist in self.indexPathsForSelectedItems , return true.
